### ISSUE TITLE
stacktraceErr should take presidence over err

### ISSUE THREAD

**Issue by blittle** [CanopyTax/auto-trace#2]
https://github.com/CanopyTax/auto-trace/blob/master/src/auto-trace.js#L101

When I do the following:

``` javascript
const trace = throwAsyncStacktrace();
setTimeout(() => {
  trace('some stringed error');
}, 1000);
```

The stack trace for the original trace error is ignored in favor of the error created inside the timeout.

**Comment by internettrans** [comment]
Fixed with https://github.com/CanopyTax/auto-trace/pull/3
